source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'7.0'

target ‘XIos’ do
    pod 'AFNetworking' #,'~> 2.5.0'
    pod 'MBProgressHUD'#, "~> 0.9"
    pod 'SVProgressHUD' #,'~> 1.0'
    pod 'BlocksKit'
    pod 'FMDB' #,'~> 2.3'
end
