package de.greenrobot.testdao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.testdao.Addresse;

import de.greenrobot.testdao.AddresseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addresseDaoConfig;

    private final AddresseDao addresseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addresseDaoConfig = daoConfigMap.get(AddresseDao.class).clone();
        addresseDaoConfig.initIdentityScope(type);

        addresseDao = new AddresseDao(addresseDaoConfig, this);

        registerDao(Addresse.class, addresseDao);
    }
    
    public void clear() {
        addresseDaoConfig.getIdentityScope().clear();
    }

    public AddresseDao getAddresseDao() {
        return addresseDao;
    }

}
